require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4

Metrics/BlockLength:
  Exclude:
    - 'tests/unit/bug_filter_by_product_spec.rb'

RSpec/VerifiedDoubles:
  Enabled: false

# We use `gems.rb` in this project
Bundler/GemFilename:
  EnforcedStyle: gems.rb
