version: '3'
services:
  app:
    image: onlyoffice/telegram_bugzilla_notifications:latest
    restart: always
    volumes:
      - ./last_send_bug.info:/root/onlyoffice_telegram_bugzilla_notifications/last_send_bug.info
      - ./config.yml:/root/onlyoffice_telegram_bugzilla_notifications/config.yml
  docspace:
    image: onlyoffice/telegram_bugzilla_notifications:latest
    restart: always
    volumes:
      - ./last_send_bug_docspace.info:/root/onlyoffice_telegram_bugzilla_notifications/last_send_bug.info
      - ./docspace_config.yml:/root/onlyoffice_telegram_bugzilla_notifications/config.yml
