version: '3'
services:
  app:
    build: .
    restart: always
    volumes:
      - ./last_send_bug.info:/root/onlyoffice_telegram_bugzilla_notifications/last_send_bug.info
      - ./config.yml:/root/onlyoffice_telegram_bugzilla_notifications/config.yml
