name: Ruby
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby 3.4
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
      - name: Install gem dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Check source files using `rubocop`
        run: bundle exec rubocop
      - name: Check that code 100% documented
        run: yardoc . | grep -q '100.00% documented'
      - name: Run tests
        run: rspec ./tests/unit/*
